const express = require("express");
const { auth,JWT_SECRET} = require("./auth");
const {UserModel,TodoModel} = require("./db");
const mongoose = require("mongoose");
const jwt = require("jsonwebtoken");

//connnecting the mongodb database
mongoose.connect("mongodb+srv://kunal:Dookie%401@cluster0.qsvqnpt.mongodb.net/test-1");

const app = express();
app.use(express.json());

app.post("/signup", async function(req, res) {
    const email = req.body.email;
    const password = req.body.password;
    const name = req.body.name;

    await UserModel.create({
        email: email,
        password: password,
        name: name
    })

    res.json({
        msg:"You are logged in"
    }) 
});


app.post("/signin", async function(req, res) {
    const email = req.body.email;
    const password = req.body.password;

    const response = await UserModel.findOne({
        email:email,
        password:password
    })

    if(response){
        const token = jwt.sign({
            id:response._id.toString() //this _id is automatically generated by the mongodb and is used to identify a user
        },JWT_SECRET);                 //the _id is a json object so we have to parse it to string using toString()
        res.json({
            token:token
        });
    }else{
        res.status(403).json({
            msg:"Incorrect credentials"
        });
    }
});


app.post("/todo",auth,async function(req, res) {
    const userId = req.userId;
    const title = req.body.title;
    const done = req.body.done;

    await TodoModel.create({
        userId:userId,
        title:title,
        done:done
    });

    res.json({
        msg: "Todo created"
    })
});


app.get("/todos",auth,async function(req, res) {
    const userId = req.userId;

    const todos = await TodoModel.find({
        userId
    })

    res.json({
        todos:todos
    })
});

app.listen(3000);